# Code Highlight theme
# Available value:
#    normal | night | night yilia | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
# night yilia - https://github.com/litten/hexo-theme-yilia
highlight_theme: night

sidebar: false # whether or not using Sidebar.
# sidebar-avatar: img/ironman-draw.png # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
  #   - featured-tags
  - short-about
#   - recent-posts
#   - friends-blog
#   - archive
#   - category
